### ISSUE TITLE
DNS resolver

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti-rest#15]
I think the current DNS resolver doesn't use tor. So an outside network observer can see the DNS resolve request.

- Is this a problem?
- Should we use the Tor DNS resolver (if there is such a thing)?

**Comment by wouterl** [comment]
Tor should directly support hostnames as part of setting up the connection, e.g., see here: https://github.com/torproject/torspec/blob/1850a1ebe730f206dd05557cf81461d9613c26b9/tor-spec.txt#L1690. So there should be no need to manually do a DNS resolve.

**Comment by ineiti** [comment]
Yes, true. There was a `DNSNameRef::try_from_ascii_str` call, and I thought it'd do a DNS lookup. But in fact it just converts the string. So all is OK...
