### ISSUE TITLE
Passing dir info to Arti

### ISSUE THREAD

**Issue by laurent-girod** [c4dt/arti-rest#35]
Could we replace the files holding the directory-information with strings?

Else we'd load the file in the mobile app, pass it as a string to the FFI-interface, store it as a file, read it again in Arti.

**Comment by ineiti** [comment]
Keep it as files for the moment, wait for Ubique to tell us to change it.

**Comment by wouterl** [comment]
Proposal. The app creates _one_ directory. This directory contains 4 files:

 * The directory authority certificate + configuration file. These files should ideally be hard-coded in the app
 * The consensus and micro descriptor files. These files should be dynamically downloaded and updated
