### ISSUE TITLE
Add scripts to repo

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti-rest#39]
For the sideloading of the directory-information, I propose we add two scripts:

- `create-keypair.py` for creation of a new keypair and a certificate
- `create-dirinfo.py` to create the consensus and microdescriptor file

and the most important of all

- `README.md` explaining how to use these files, linked from the main README.md

**Comment by laurent-girod** [comment]
Tor already provide a command to generate keypairs and certificate, `tor-gencert`, which can also be used to generate identity keys for authorities.
Should I create a python script to wrap around it with the right parameters?

**Comment by ineiti** [comment]
I started a PR #42. Please have a look at it and change what needs to be changed.

**Comment by laurent-girod** [comment]
The `gen_fresh_dirinfo.py` script can be used to generate the directory authority's keys and certificate now that #56 have been merged into main.
