### ISSUE TITLE
Make custom directory authority configurable

### ISSUE THREAD

**Issue by wouterl** [c4dt/arti-rest#41]
Currently our custom directory authority (DA) is hard-coded in arti-rest. Instead arti-rest should have the option to set -- at runtime -- the directory authority and corresponding values.

**Comment by wouterl** [comment]
See also issue #35

**Comment by laurent-girod** [comment]
The directory authority is now configurable. I propose that we close this issue?

**Comment by ineiti** [comment]
Absolutely. In fact you can add

```
Closes #41
```

to the description of a PR. Then, when the PR is merged, the issue is automagically closed!

Anyway, to you the honours to click the `Close` button!
