### ISSUE TITLE
READMEs

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti-rest#46]
Update the READMEs with big warnings saying that:

- this is based on arti, which claims "no security" (yet)
- it is an extended version with side-loading of the nodes

This should be done for all related repos:
- arti-rest
- arti-ios
- arti-android

**Comment by cgrigis** [comment]
Add minimal info in https://github.com/c4dt/arti-android README.

**Comment by wouterl** [comment]
This README looks good now, `arti-ios` looks good as well. Added similar warning to `arti-android`.
