### ISSUE TITLE
Panic handling

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti-rest#47]
There seem to be some panics left:

- check if it's just an `unwrap`, and convert it to a `context()?`
- look with @ubamrein if it's possible to recover from a panic in rust

**Comment by ubamrein** [comment]
Since we use `abort` panics (at least on iOS if I remember correctly), I am not really sure, if there is an easy and safe way. I know you can provide your custom [panic hook though](https://doc.rust-lang.org/std/panic/fn.set_hook.html) I am uncertain if you can continue execution after that.

**Comment by ineiti** [comment]
I think we removed the abort-panic from the `Crate.toml`. Would it be possible to just return an error to the mobile part?

**Comment by ubamrein** [comment]
There is also [`catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html), so we could catch the panic as long as it happens somewhere we can catch it :)

**Comment by ineiti** [comment]
iOS #52 needs to pass tests...

**Comment by cgrigis** [comment]
Can we close this now?

**Comment by ineiti** [comment]
Of course - we found the bug in #52, so all is good now.
