### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti-rest#5]
@ubamrein wrote on slack:

Maybe it is already obvious but I just input some of my thoughts:
I think you should as soon as possible specify the API and make it stable in the sense that iOS and Android specific ffi code should not really care, what version of arti (or if you use arti at all) you are using :slightly_smiling_face:
So my proposal would be:
* lib.rs -> contains the stable api code for the rest api, code here is allowed to call code in any submodule except android or ios
* android.rs -> contains ffi code ONLY using functions available in lib.rs
* ios.rs -> contains ffi code ONLY using functions available in lib.rs
* arti.rs -> crazy tor logic, config loading, tls stuff whatever

**Comment by ineiti** [comment]
Sounds great to me. If somebody starts working on this, please assign the issue to you, so that others don't do the same.

One question: why do you want to separate the `lib.rs` and `arti.rs`? Would `arti.rs` be the basic response handler, and `lib.rs` implement the GET, POST, ... stuff?

**Comment by ubamrein** [comment]
In `lib.rs` I would only put the public api code. For example the `Request` struct, implementations thereof and convenience functions.

Handling of config file loading, preparing the Runtime and such I would put into submodules to `lib.rs`. That way you have an easy to read public api. And if e.g. if there at one point are multiple tor implementations, it is easier to switch between them in the `lib.rs`. I guess it is not really needed here you are right. It just looks nicer, when the `lib.rs` is cleaner :D
