### ISSUE TITLE
Split iOS, Android, support library

### ISSUE THREAD

**Issue by ineiti** [c4dt/arti-rest#6]
@ubamrein proposes:

If you want to go one step further, you could split ios, android and core into three crates. So you don’t have to compile (or clutter the code with #[cfg]s) for different platforms, which means your library gets smaller (as only the symbols of the specific platform is included).
Further, it makes development a bit easier, as the core IR product can be shared between iOS and Android, such that working on the platform specific code, can build faster :slightly_smiling_face:
As a neat bonus, you could also provide the API to desktop apps or CLIs :wink:

**Comment by ineiti** [comment]
Wait, if I use `#[cfg`, the code is included anyway, even if it's not active?

**Comment by ubamrein** [comment]
> Wait, if I use `#[cfg`, the code is included anyway, even if it's not active?
No , I overlooked the #[cfg]s on the ffi imports :)

**Comment by ineiti** [comment]
OK, I'm still new to rust, even after half a year of coding nearly daily I'm still surprised by some stuff. So everything is possible ;)

**Comment by ineiti** [comment]
Closing this, as the `#[cfg` will take care of this.
