### ISSUE TITLE
Minimal consensus and descriptors for arti

### ISSUE THREAD

**Issue by wouterl** [c4dt/arti-rest#8]
The full consensus and descriptors are big. We want to create a custom smaller set that is stable enough so that frequent updates are not necessary. This involves the following steps:

- [ ] Script to create smaller version of consensus + descriptors (says top 256 stable nodes; pick nodes with Stable flags set, pick higher-bandwidth nodes)
- [ ] Side-load these files into Arti (e.g., from file or in-memory String)

I think Tor can already query for a batch of microdescriptors; so probably want to reuse that format. Alternatively, we can modify Arti to download these via URL that we pass as config if that is easier to do.

Ideally, this would be an extension on top of arti so that we don't have to fork `arti` proper, but that might not be possible at the moment.

**Comment by wouterl** [comment]
@laurent-girod is this done?

**Comment by laurent-girod** [comment]
Yes, this is done via the script `gen_fresh_dirinfo-py`.
